Server:
  Mode: release
  Port: :9090
  DbAutoMigrate: false
  DbLogMode: "info"
Mysql:
  Host: 127.0.0.1
  Port: 3306
  Config: "charset=utf8mb4&parseTime=True&loc=Local"
  Dbname: "gin_blog"
  Username: root
  Password: 12345678
Jwt:
  JwtKey: "242m6etvj5"
  ExpireDays: 7
Session:
  Name: "gin-blog"
  Salt: "salt"
  MaxAge: 600

